//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ankiety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int Adres_ID { get; set; }
        public int AdresTyp_ID { get; set; }
        public Nullable<int> AdresKraj_ID { get; set; }
        public string AdresMiasto { get; set; }
        public string AdresKod { get; set; }
        public string AdresUlicaTyp { get; set; }
        public string AdresUlica { get; set; }
        public string AdresUlicaNR { get; set; }
        public string AdresWojewodztwo { get; set; }
    
        public virtual AdresKraj AdresKraj { get; set; }
        public virtual AdresTyp AdresTyp { get; set; }
    }
}
