//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ankiety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnkietaWzor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnkietaWzor()
        {
            this.Ankieta = new HashSet<Ankieta>();
            this.AnkietaWzorPytanie = new HashSet<AnkietaWzorPytanie>();
        }
    
        public int AnkietaWzor_ID { get; set; }
        public string NazwaAnkiety { get; set; }
        public string Wersja { get; set; }
        public Nullable<bool> Aktywna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ankieta> Ankieta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnkietaWzorPytanie> AnkietaWzorPytanie { get; set; }
    }
}
