//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ankiety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnkietaWzorPytanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnkietaWzorPytanie()
        {
            this.AnkietaWzorOdpowiedz = new HashSet<AnkietaWzorOdpowiedz>();
        }
    
        public int AnkietaWzorPytanie_ID { get; set; }
        public Nullable<int> AnkietaWzor_ID { get; set; }
        public Nullable<int> Pytanie_LP { get; set; }
        public string Pytanie { get; set; }
        public Nullable<int> OdpowiedzTyp { get; set; }
    
        public virtual AnkietaWzor AnkietaWzor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnkietaWzorOdpowiedz> AnkietaWzorOdpowiedz { get; set; }
    }
}
