//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ankiety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ankieta
    {
        public int Ankieta_ID { get; set; }
        public Nullable<int> AnkietaWzor_ID { get; set; }
        public Nullable<int> Pytanie_LP { get; set; }
        public Nullable<int> Odp_LP { get; set; }
        public string StanAnkiety { get; set; }
        public string Odpowiedz { get; set; }
    
        public virtual AnkietaWzor AnkietaWzor { get; set; }
        public virtual StazStudentAnkieta StazStudentAnkieta { get; set; }
        public virtual StazStudentAnkieta StazStudentAnkieta1 { get; set; }
    }
}
