//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ankiety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UmowaWzorZmienne
    {
        public int UmowaWzorZmienne_ID { get; set; }
        public Nullable<int> UmowaWzor_ID { get; set; }
        public string ZmiennaNazwa { get; set; }
        public string ZmiennaDefinicja { get; set; }
    
        public virtual UmowaWzor UmowaWzor { get; set; }
    }
}
