//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ankiety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UmowaWzor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UmowaWzor()
        {
            this.Umowa = new HashSet<Umowa>();
            this.UmowaWzorZmienne = new HashSet<UmowaWzorZmienne>();
        }
    
        public int UmowaWzor_ID { get; set; }
        public string UmowaNazwa { get; set; }
        public Nullable<bool> AktywnyWzor { get; set; }
        public string Wersja { get; set; }
        public string TrescUmowy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Umowa> Umowa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UmowaWzorZmienne> UmowaWzorZmienne { get; set; }
    }
}
