//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ankiety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Umowa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Umowa()
        {
            this.UmowaZmienne = new HashSet<UmowaZmienne>();
        }
    
        public int Umowa_ID { get; set; }
        public string UmowaNR { get; set; }
        public Nullable<int> UmowaWzor_ID { get; set; }
        public string TrescUmowy { get; set; }
    
        public virtual UmowaWzor UmowaWzor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UmowaZmienne> UmowaZmienne { get; set; }
    }
}
