//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ankiety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UmowaZmienne
    {
        public int UmowaZmienne_ID { get; set; }
        public Nullable<int> Umowa_ID { get; set; }
        public string ZmiennaNazwa { get; set; }
        public string ZmiennaWartosc { get; set; }
    
        public virtual Umowa Umowa { get; set; }
    }
}
